{
    'name': 'Menu',
    'version': '1.0',
    'depends': ['base', 'website'],
    'data': [
        'views/dashboard_template.xml',
        'security/acs_register_category.xml',
        'security/acs_register_security.xml',
        'security/ir.model.access.csv',
        'views/empty_view.xml',
        'views/coming_plan_views.xml',
        'views/gate_view.xml',
        'views/lane_view.xml',
        'views/plant_view.xml',
        'views/building_view.xml',
        'views/company_view.xml',
        'views/department_view.xml',
        'views/job_position_view.xml',
        'views/register_vehicle_type_views.xml',
        'views/purpose_of_visit_views.xml',
        'views/data_control_in_out.xml',
        'views/control_in_out_template.xml',
        'views/transaction_type.xml',
        'views/custom_report_layout.xml',
        'views/report_acs_register.xml',
        'views/report_acs_register_action.xml',
        'views/visitor_vehicles_views.xml',
        'views/maintenance_vehicles_views.xml',
        'views/whitelist_view.xml',
        'views/logistic_view.xml',
        'actions/acs_register_actions.xml',
        'actions/maintenance_vehicles_actions.xml',
        'actions/whitelist_actions.xml',
        'actions/logistic_actions.xml',
        'views/res_reason_view.xml',
        'views/menu_views.xml',
        'views/wizard_reject_reason_views.xml',
        'data/email_templates.xml',
    ],
    'assets': {
            'web.assets_frontend': [
                '/menu/static/src/js/custom_notification.js',
                '/menu/static/src/css/custom_style.css',
                '/menu/static/src/js/notification_bell.js',
            ],
    },
    'installable': True,
    'application': True,
}
